import turtle
numeros = []

# Crea la ventana
turtle.reset()
turtle.setup(600,350)
turtle.speed(0)

# Dibuja el display
turtle.penup()
turtle.goto(-275,150)
turtle.fillcolor("#2db300")
turtle.begin_fill()
turtle.pendown()
turtle.forward(550)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(550)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

# Dibuja el boton 1
turtle.penup()
turtle.goto(-275,90)
turtle.seth(0)
turtle.fillcolor("#ff6600")
turtle.pendown()
turtle.begin_fill()
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()


# Dibuja el boton 2
turtle.penup()
turtle.goto(-140,90)
turtle.seth(0)
turtle.fillcolor("#ff6600")
turtle.pendown()
turtle.begin_fill()
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

# Dibuja el boton 3
turtle.penup()
turtle.goto(-5,90)
turtle.seth(0)
turtle.fillcolor("#ff6600")
turtle.pendown()
turtle.begin_fill()
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

# Dibuja el boton +
turtle.penup()
turtle.goto(150,90)
turtle.seth(0)
turtle.fillcolor("#66a3ff")
turtle.pendown()
turtle.begin_fill()
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

# Dibuja el boton 4
turtle.penup()
turtle.goto(-275,30)
turtle.seth(0)
turtle.fillcolor("#ff6600")
turtle.pendown()
turtle.begin_fill()
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

# Dibuja el boton 5
turtle.penup()
turtle.goto(-140,30)
turtle.seth(0)
turtle.fillcolor("#ff6600")
turtle.pendown()
turtle.begin_fill()
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

# Dibuja el boton 6
turtle.penup()
turtle.goto(-5,30)
turtle.seth(0)
turtle.fillcolor("#ff6600")
turtle.pendown()
turtle.begin_fill()
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

# Dibuja el boton -
turtle.penup()
turtle.goto(150,30)
turtle.seth(0)
turtle.fillcolor("#66a3ff")
turtle.pendown()
turtle.begin_fill()
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

# Dibuja el boton 7
turtle.penup()
turtle.goto(-275,-30)
turtle.seth(0)
turtle.fillcolor("#ff6600")
turtle.pendown()
turtle.begin_fill()
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

# Dibuja el boton 8
turtle.penup()
turtle.goto(-140,-30)
turtle.seth(0)
turtle.fillcolor("#ff6600")
turtle.pendown()
turtle.begin_fill()
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

# Dibuja el boton 9
turtle.penup()
turtle.goto(-5,-30)
turtle.seth(0)
turtle.fillcolor("#ff6600")
turtle.pendown()
turtle.begin_fill()
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

# Dibuja el boton x
turtle.penup()
turtle.goto(150,-30)
turtle.seth(0)
turtle.fillcolor("#66a3ff")
turtle.pendown()
turtle.begin_fill()
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

# Dibuja el boton AC
turtle.penup()
turtle.goto(-275,-90)
turtle.seth(0)
turtle.fillcolor("#66a3ff")
turtle.pendown()
turtle.begin_fill()
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

# Dibuja el boton 0
turtle.penup()
turtle.goto(-140,-90)
turtle.seth(0)
turtle.fillcolor("#ff6600")
turtle.pendown()
turtle.begin_fill()
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

# Dibuja el boton =
turtle.penup()
turtle.goto(-5,-90)
turtle.seth(0)
turtle.fillcolor("#66a3ff")
turtle.pendown()
turtle.begin_fill()
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

# Dibuja el boton /
turtle.penup()
turtle.goto(150,-90)
turtle.seth(0)
turtle.fillcolor("#66a3ff")
turtle.pendown()
turtle.begin_fill()
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(125)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

# Dibuja el label de los botones
turtle.penup()
turtle.goto(-213,45)
turtle.pendown()
turtle.pencolor("white")
turtle.write("1", align='center', font=('Arial',24,'bold'))

turtle.penup()
turtle.goto(-78,45)
turtle.pendown()
turtle.pencolor("white")
turtle.write("2", align='center', font=('Arial',24,'bold'))

turtle.penup()
turtle.goto(57,45)
turtle.pendown()
turtle.pencolor("white")
turtle.write("3", align='center', font=('Arial',24,'bold'))

turtle.penup()
turtle.goto(212,45)
turtle.pendown()
turtle.pencolor("white")
turtle.write("+", align='center', font=('Arial',24,'bold'))

turtle.penup()
turtle.goto(-213,-15)
turtle.pendown()
turtle.pencolor("white")
turtle.write("4", align='center', font=('Arial',24,'bold'))

turtle.penup()
turtle.goto(-78,-15)
turtle.pendown()
turtle.pencolor("white")
turtle.write("5", align='center', font=('Arial',24,'bold'))

turtle.penup()
turtle.goto(57,-15)
turtle.pendown()
turtle.pencolor("white")
turtle.write("6", align='center', font=('Arial',24,'bold'))

turtle.penup()
turtle.goto(212,-15)
turtle.pendown()
turtle.pencolor("white")
turtle.write("-", align='center', font=('Arial',24,'bold'))

turtle.penup()
turtle.goto(-213,-75)
turtle.pendown()
turtle.pencolor("white")
turtle.write("7", align='center', font=('Arial',24,'bold'))

turtle.penup()
turtle.goto(-78,-75)
turtle.pendown()
turtle.pencolor("white")
turtle.write("8", align='center', font=('Arial',24,'bold'))

turtle.penup()
turtle.goto(57,-75)
turtle.pendown()
turtle.pencolor("white")
turtle.write("9", align='center', font=('Arial',24,'bold'))

turtle.penup()
turtle.goto(212,-75)
turtle.pendown()
turtle.pencolor("white")
turtle.write("x", align='center', font=('Arial',24,'bold'))

turtle.penup()
turtle.goto(-213,-135)
turtle.pendown()
turtle.pencolor("white")
turtle.write("AC", align='center', font=('Arial',24,'bold'))

turtle.penup()
turtle.goto(-78,-135)
turtle.pendown()
turtle.pencolor("white")
turtle.write("0", align='center', font=('Arial',24,'bold'))

turtle.penup()
turtle.goto(57,-135)
turtle.pendown()
turtle.pencolor("white")
turtle.write("=", align='center', font=('Arial',24,'bold'))

turtle.penup()
turtle.goto(212,-135)
turtle.pendown()
turtle.pencolor("white")
turtle.write("/", align='center', font=('Arial',24,'bold'))

# Definicion de la funcion que determina que boton se pulso
def deteccionClick(x,y):
    if(x > -275 and x < -150 and y > 40 and y < 90):
            turtle.penup()
            turtle.goto(250,110)
            numeros.append(1)
            turtle.pendown()
            turtle.penup()
            turtle.goto(-275,150)
            
    if(x > -140 and x < -15 and y > 40 and y < 90):
            turtle.penup()
            turtle.goto(250,110)
            numeros.append(1)
            turtle.pendown()
            turtle.penup()
            turtle.goto(-275,150)
            turtle.fillcolor("#2db300")
            turtle.begin_fill()
            turtle.pendown()
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.right(90)
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.end_fill()
            turtle.penup()
            turtle.goto(-275,150)
            turtle.fillcolor("#2db300")
            turtle.begin_fill()
            turtle.pendown()
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.right(90)
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.end_fill()
            turtle.penup()
            numeros.append(2)
            turtle.goto(260,120)
            turtle.pendown()
            turtle.pencolor("white")
            turtle.write(numeros, align='center', font=('Arial',24,'bold'))
            print(x,y)
        
    if(x > -5 and x < 120 and y > 40 and y < 90):
            turtle.penup()
            turtle.goto(250,110)
            numeros.append(1)
            turtle.pendown()
            turtle.penup()
            turtle.goto(-275,150)
            turtle.fillcolor("#2db300")
            turtle.begin_fill()
            turtle.pendown()
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.right(90)
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.end_fill()
            turtle.penup()
            turtle.goto(-275,150)
            turtle.fillcolor("#2db300")
            turtle.begin_fill()
            turtle.pendown()
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.right(90)
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.end_fill()
            turtle.penup()
            numeros.append(3)
            turtle.goto(250,110)
            turtle.pendown()
            turtle.pencolor("white")
            turtle.write(numeros , align='center', font=('Arial',24,'bold'))
            print(x,y)

    if(x > 140 and x < 265 and y > 40 and y < 90):
            turtle.penup()
            turtle.goto(250,110)
            numeros.append(1)
            turtle.pendown()
            turtle.penup()
            turtle.goto(-275,150)
            turtle.fillcolor("#2db300")
            turtle.begin_fill()
            turtle.pendown()
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.right(90)
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.end_fill()
            turtle.penup()
            turtle.goto(-275,150)
            turtle.fillcolor("#2db300")
            turtle.begin_fill()
            turtle.pendown()
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.right(90)
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.end_fill()
            turtle.penup()
            turtle.goto(250,110)
            numeros.append(4)
            turtle.pendown()
            turtle.pencolor("white")
            turtle.write(numeros , align='center', font=('Arial',24,'bold'))
            print(x,y)

    if(x > -110 and x < 80 and y > 40 and y < 90):
            turtle.penup()
            turtle.goto(250,110)
            numeros.append(1)
            turtle.pendown()
            turtle.penup()
            turtle.goto(-275,150)
            turtle.fillcolor("#2db300")
            turtle.begin_fill()
            turtle.pendown()
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.right(90)
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.end_fill()
            turtle.penup()
            turtle.goto(-275,150)
            turtle.fillcolor("#2db300")
            turtle.begin_fill()
            turtle.pendown()
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.right(90)
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.end_fill()
            turtle.penup()
            turtle.goto(250,110)
            numeros.append(5)
            turtle.pendown()
            turtle.pencolor("white")
            turtle.write(numeros , align='center', font=('Arial',24,'bold'))
            print(x,y)

    if(x > -100 and x < 70 and y > 40 and y < 90):
            turtle.penup()
            turtle.goto(250,110)
            numeros.append(1)
            turtle.pendown()
            turtle.penup()
            turtle.goto(-275,150)
            turtle.fillcolor("#2db300")
            turtle.begin_fill()
            turtle.pendown()
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.right(90)
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.end_fill()
            turtle.penup()
            turtle.goto(-275,150)
            turtle.fillcolor("#2db300")
            turtle.begin_fill()
            turtle.pendown()
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.right(90)
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.end_fill()
            turtle.penup()
            turtle.goto(250,110)
            numeros.append(6)
            turtle.pendown()
            turtle.pencolor("white")
            turtle.write(numeros , align='center', font=('Arial',24,'bold'))
            print(x,y)

    if(x > -90 and x < 60 and y > 40 and y < 90):
            turtle.penup()
            turtle.goto(250,110)
            numeros.append(1)
            turtle.pendown()
            turtle.penup()
            turtle.goto(-275,150)
            turtle.fillcolor("#2db300")
            turtle.begin_fill()
            turtle.pendown()
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.right(90)
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.end_fill()
            turtle.penup()
            turtle.goto(-275,150)
            turtle.fillcolor("#2db300")
            turtle.begin_fill()
            turtle.pendown()
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.right(90)
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.end_fill()
            turtle.penup()
            turtle.goto(250,110)
            numeros.append(7)
            turtle.pendown()
            turtle.pencolor("white")
            turtle.write(numeros , align='center', font=('Arial',24,'bold'))
            print(x,y)

    if(x > -80 and x < 50 and y > 40 and y < 90):
            turtle.penup()
            turtle.goto(250,110)
            numeros.append(1)
            turtle.pendown()
            turtle.penup()
            turtle.goto(-275,150)
            turtle.fillcolor("#2db300")
            turtle.begin_fill()
            turtle.pendown()
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.right(90)
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.end_fill()
            turtle.penup()
            turtle.goto(-275,150)
            turtle.fillcolor("#2db300")
            turtle.begin_fill()
            turtle.pendown()
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.right(90)
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.end_fill()
            turtle.penup()
            turtle.goto(250,110)
            numeros.append(8)
            turtle.pendown()
            turtle.pencolor("white")
            turtle.write(numeros, align='center', font=('Arial',24,'bold'))
            print(x,y)

    if(x > -70 and x < 40 and y > 40 and y < 90):
            turtle.penup()
            turtle.goto(250,110)
            numeros.append(1)
            turtle.pendown()
            turtle.penup()
            turtle.goto(-275,150)
            turtle.fillcolor("#2db300")
            turtle.begin_fill()
            turtle.pendown()
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.right(90)
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.end_fill()
            turtle.penup()
            turtle.goto(-275,150)
            turtle.fillcolor("#2db300")
            turtle.begin_fill()
            turtle.pendown()
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.right(90)
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.end_fill()
            a.append(9)
            turtle.penup()
            turtle.goto(250,110)
            numeros.append(9)
            turtle.pendown()
            turtle.pencolor("white")
            turtle.write(numeros , align='center', font=('Arial',24,'bold'))
            print(x,y)

    if(x > -60 and x < 30 and y > 40 and y < 90):
            turtle.penup()
            turtle.goto(250,110)
            numeros.append(1)
            turtle.pendown()
            turtle.penup()
            turtle.goto(-275,150)
            turtle.fillcolor("#2db300")
            turtle.begin_fill()
            turtle.pendown()
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.right(90)
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.end_fill()
            turtle.penup()
            turtle.goto(-275,150)
            turtle.fillcolor("#2db300")
            turtle.begin_fill()
            turtle.pendown()
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.right(90)
            turtle.forward(550)
            turtle.right(90)
            turtle.forward(50)
            turtle.end_fill()
            turtle.penup()
            turtle.goto(250,110)
            numeros.append(0)
            turtle.pendown()
            turtle.pencolor("white")
            turtle.write(numeros, align='center', font=('Arial',24,'bold'))
            print(x,y)

# Detecta el click del mouse
turtle.onscreenclick(deteccionClick)

# Esconde la tortuga
turtle.hideturtle()
